export const MENU_DATA = [
    {
        id: "1",
        itemLevel: 1,
        parentId: 0,
        itemName: "代理机构管理",
        route: "/agencyOrg",
        icon: "agencyOrg",
        children: [],
    },
    {
        id: "2",
        itemLevel: 1,
        parentId: 0,
        itemName: "保险机构管理",
        route: "/insuranceOrg",
        icon: "insuranceOrg",
        children: [],
    },
    {
        id: "3",
        itemLevel: 1,
        parentId: 0,
        itemName: "线索机构管理",
        route: "/cluesOrg",
        icon: "cluesOrg",
        children: [],
    },
    {
        id: "4",
        itemLevel: 1,
        parentId: 0,
        itemName: "险种分类管理",
        route: "/insuranceType",
        icon: "insuranceType",
        children: [],
    },
    {
        id: "5",
        itemLevel: 1,
        itemName: "意向线索管理",
        parentId: 0,
        route: "/intentionClues",
        icon: "intentionClues",
        children: [],
    },
    {
        id: "6",
        itemLevel: 1,
        parentId: 0,
        itemName: "产品管理",
        route: "/product",
        icon: "product",
        children: [],
    },
    {
        id: "7",
        itemLevel: 1,
        parentId: 0,
        itemName: "线索管理",
        route: "/clues",
        icon: "clues",
        children: [],
    },
    {
        id: "8",
        itemLevel: 1,
        parentId: 0,
        itemName: "线索分配 ",
        route: "/cueAllocation",
        icon: "cueAllocation",
        children: [],
    },
    {
        id: "9",
        itemLevel: 1,
        parentId: 0,
        itemName: "保单管理",
        route: "/order",
        icon: "order",
        children: [],
    },
    {
        id: "10",
        itemLevel: 1,
        parentId: 0,
        itemName: "数据统计",
        route: "/statistics",
        icon: "statistics",
        children: [],
    },
]
